production:
  ignore_errors:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
    - ActiveRecord::QueryCanceled
    - PG::QueryCanceled
    - Rack::Timeout::RequestTimeoutException